### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by theAkito** [JanHolger/rancher-api-v3-java#1]
Greetings,

thank you for this project.

Care to give it a license? I personally would recommend either [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.html), as these are among the most popular ones and probably would fit this project well, as it usually does with most projects on Github.

**Comment by theAkito** [comment]
Whatever man, not using this library anymore, anyway.

**Comment by JanHolger** [comment]
Sorry for not answering in time! Unfortunately I didn't have any notification for the issue and I also didn't expect anyone to use it but I thought it would be a good idea to open source it as there is no real documentation on the api. I just forgot to add any license file and added it now.
